FROM nginx:alpine
COPY . /usr/share/nginx/html
#RUN rm /etc/nginx/conf.d/default.conf какое коварство) nginx.conf который был в репе больше походит на default.conf. если не требуется тонкой настройки берем дефолтный из nginx:alpine